### PR TITLE
#23 Use Retrofit instead of Volley to make Network requests

### PR DESCRIPTION
**Pull request by eXeeLD**
# 23 Fixed

### CODE REVIEW

**Comment by dr0pdb** [comment]
Please don't add everything in one PR. Create separate PR for each issue.

**Comment by eXeeLD** [comment]
@srv-twry  if i understood it right , i need to create a new branch for every issue then open pr from that branch, tell me if i'm wrong , i'm new to the pr

**Comment by dr0pdb** [comment]
Yes, you're right. This helps find the source of any possible errors/bugs in the future if they occur.
[This](https://medium.com/@fagnerbrack/one-pull-request-one-concern-e84a27dfe9f1) would be a good read to consolidate this idea

**Comment by eXeeLD** [comment]
thank you , now i'm on the #14 i opened a branch and now doing home activity , when i finish i will open a new pr

**Pull request closed without merging**
